import { defineConfig } from 'vite'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    nodePolyfills({
      exclude: [
        'assert',
        'buffer',
        'child_process',
        'cluster',
        'console',
        'constants',
        'crypto',
        'dgram',
        'dns',
        'domain',
        'events',
        'fs',
        'http',
        'https',
        'http2',
        'module',
        'net',
        'os',
        'path',
        'punycode',
        'process',
        'querystring',
        'readline',
        'repl',
        'stream',
        '_stream_duplex',
        '_stream_passthrough',
        '_stream_readable',
        '_stream_transform',
        '_stream_writable',
        'string_decoder',
        'sys',
        'timers/promises',
        'tls',
        'tty',
        'url',
        'util',
        'vm',
        'zlib',
      ],
      protocolImports: false,
    }),
  ],
});
